mainpage/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'mainpage'

urlpatterns = [

    # http://127.0.0.1:8000/
    path('', views.push_to_news, name='home'),

    # /habrahabr/category/3/
    url('habrahabr/category/(?P<slug>[\w-]+)/$', views.categories, name='habr_list'),

    # /tut/category/9/
    url('tut/category/(?P<slug>[\w-]+)/$', views.categories, name='tut_list'),

    # habrahabr/category/3/post/1910
    url(r'^(habrahabr|tut)/category/(?P<slug>[\w-]+)/post/(?P<pk>\d+)/$', views.PostDetailView.as_view(),
        name='news_detail'),

    # post/1910
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post'),

    # /create
    path('create', views.NewsCreateView.as_view(), name='news_create'),

    # post/1910/update
    url(r'^post/(?P<pk>\d+)/update$', views.NewsUpdateView.as_view(), name='news_update'),

    # post/1910/delete
    url(r'^post/(?P<pk>\d+)/delete$', views.NewsDeleteView.as_view(), name='news_delete'),

    path('register', views.UserRegister.as_view(), name='register'),

    path('login', views.UserLogin.as_view(), name='login'),

    path('logout', views.logout_view, name='logout'),

    path('news', views.CustomPostView.as_view(), name='custom_posts'),

    path('moderating', views.NewsOnModerationView.as_view(), name='posts_on_moderation'),

    path('activate/<str:token>/', views.ActivateView.as_view(), name='activate'),

    url(r'^account/profile/favourites/post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_favours'),

    url(r'user/favorited$', views.favorite_toggle, name='fav_toggle'),

    url(r'user/moderated$', views.moderator_toggle, name='mod_toggle'),

    url(r'^account/profile/favourites/$', views.ProfileFavourites.as_view(),
      name='favourites'),

    path('account/profile/update', views.ProfileUpdateView.as_view(), name='update_profile'),

    url(r'account/profile', views.ProfileView.as_view(), name='profile'),


    url(r'password_change/$', auth_views.PasswordChangeView.as_view(template_name='mainpage/change-password.html',
                                                       success_url='/accounts/password_change_done'),
        name='change_password'),

    url(r'password_change_done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='mainpage/password_change_done.html'),
        name='change_password_done'),

    url(r'password_reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='mainpage/registration/password_reset_form.html',
            email_template_name='mainpage/registration/password_reset_email.html',
            subject_template_name='mainpage/registration/password_reset_subject.txt',
            success_url='/accounts/password_reset_done/', from_email='support@jamba.by'),
        name='password_reset'),

    url(r'password_reset_done/',
        auth_views.PasswordResetDoneView.as_view(template_name='mainpage/registration/password_reset_done.html')),

    url(r'password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='mainpage/registration/password_reset_confirm.html',
                                                    success_url='/accounts/password_reset_complete/'),
        name='password_reset_confirm'),

    url(r'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='mainpage/registration/password_reset_complete.html')),



]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('mainpage.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpage/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models
import datetime
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

NULL_BLANK = {
    'null': True,
    'blank': True
}


# Модель номер 1. Новостные сайты
class Sites(models.Model):

    name = models.CharField(max_length=100, **NULL_BLANK)

    url = models.CharField(max_length=100, **NULL_BLANK)

    class Meta:
        verbose_name = 'Сайт'
        verbose_name_plural = 'Сайты'

    def __str__(self):
        return self.name


# Модель номер 2. Категории с этих сайтов
class Categories(models.Model):

    headline = models.CharField(max_length=100, **NULL_BLANK)

    url = models.CharField(max_length=100, **NULL_BLANK)

    site = models.ForeignKey(to='Sites', on_delete=models.CASCADE, default=12)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.headline


# Модель номер 3. Новостные посты из этих категорий
class Post(models.Model):

    url = models.SlugField(max_length=255, **NULL_BLANK)

    create_date = models.CharField(max_length=255, **NULL_BLANK,
                                   default=datetime.datetime.now().strftime('%d/%m, %H:%M'))

    publish_time = models.DateTimeField(default=now)

    is_published = models.BooleanField(default=False)

    title = models.CharField(verbose_name=_('Название'), max_length=255, **NULL_BLANK)

    preview = models.TextField(verbose_name=_('Предпросмотр'), **NULL_BLANK)

    content = models.TextField(verbose_name=_('Контент'), **NULL_BLANK)

    categories = models.ForeignKey(to='Categories', on_delete=models.CASCADE, default=999)

    pic = models.TextField(**NULL_BLANK)

    user = models.ForeignKey(to=User, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-publish_time']

    def __str__(self):
        return self.title


# Модель номер 4. Модель активации пользователя
class Activation(models.Model):
    valid_until = models.DateTimeField(
        verbose_name=_('Дата окончания действия ссылки активации'),
    )
    url = models.URLField(
        verbose_name=_('Ссылка'),
    )

    def set_url(self):
        import binascii
        import os
        self.url = 'activate/{token}/'.format(
            token=binascii.hexlify(os.urandom(10)).decode('utf-8')
        )
        pass


# Модель номер 5. Профиль пользователя
class Profile(models.Model):
    activation = models.OneToOneField(
        verbose_name=_('Активация'),
        to=Activation,
        on_delete=models.SET_NULL,
        **NULL_BLANK
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    avatar = models.ImageField(
        verbose_name=_('Аватар'),
        upload_to='.',
        **NULL_BLANK
    )

    post_fav = models.ManyToManyField(to=Post, blank=True)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __unicode__(self):
        return u'Profile of user: %s' % self.user.username

mainpage/views.py
from datetime import timedelta
from django.contrib import messages
from django.db import transaction
from django.views.generic import DetailView, CreateView, DeleteView, View, FormView, RedirectView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.conf import settings
from django.utils.translation import ugettext as _

import json
from .models import User, Post
from django.views.generic import UpdateView
from . import forms
from mainpage import models as mainpage_models
import logging
log = logging.getLogger(__name__)
logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%I:%M:%S %p')


# Profile
class ProfileView(LoginRequiredMixin, FormView):
    """
    Provides views with the current user's profile.
    """
    form_class = forms.ProfileUpdateMETA
    model = mainpage_models.Profile
    template_name = 'mainpage/profile.html'


# Profile Update Info
class ProfileUpdateView(LoginRequiredMixin, FormView):

    model = mainpage_models.Profile
    template_name = 'mainpage/profile_update.html'
    form_class = forms.ProfileUpdateMETA
    success_url = reverse_lazy('mainpage:profile')

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['first_name'] != '':
                User.objects.filter(username=request.user).update(
                    first_name=form.cleaned_data['first_name'])
            if form.cleaned_data['last_name'] != '':
                User.objects.filter(username=request.user).update(
                    last_name=form.cleaned_data['last_name'])
            if form.cleaned_data['avatar']:
                profile = mainpage_models.Profile.objects.filter(user=User.objects.get(username=request.user))
                profile.update(avatar=form.cleaned_data['avatar'])
                try:
                    form.save()
                except Exception:
                    pass
            return super(ProfileUpdateView, self).form_valid(form)
        else:
            return self.form_invalid(form)

    # def clean_image(self, request):
    #     image = .update
    #     if image:
    #         # do some validation, if it fails
    #         raise forms.ValidationError(u'Form error')
    #     return image

    # def post(self, request, *args, **kwargs):
    #     form = self.get_form()
    #     if form.is_valid():
    #         with transaction.atomic():
    #             try:
    #                 user = User.objects.get(username=request.user)
    #                 User.objects.create(
    #                     first_name=form.cleaned_data['first_name'],
    #                     last_name=form.cleaned_data['last_name'])
    #                 user.save()
    #
    #                 profile = mainpage_models.Profile()
    #                 profile.avatar = form.cleaned_data['avatar']
    #                 profile.save()
    #             except Exception as exc:
    #                 raise exc
    #         return self.form_valid(form)
    #     return self.form_invalid(form)


# Profile Favorite Section
class ProfileFavourites(LoginRequiredMixin, FormView):
    form_class = forms.ProfileUpdateMETA
    model = mainpage_models.Profile
    template_name = 'mainpage/favourites.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = mainpage_models.Profile(user=self.request.user)
        favourite_posts = mainpage_models.Profile.objects.filter(post_fav__profile=current_user)
        for item in favourite_posts:
            context['favourite_posts'] = item.post_fav.all()
        context['profile'] = mainpage_models.Profile.objects.all()
        return context


# News Details
class PostDetailView(DetailView):  # детализированное представление модели

    model = mainpage_models.Post
    # form_class = forms.ProfileFavPost
    template_name = 'mainpage/post_detail.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = mainpage_models.Profile.objects.all()
        try:
            for item in mainpage_models.Profile.objects.filter(user=self.request.user):
                # print(item.post_fav.all().values_list('id', flat=True))
                context['favs'] = item.post_fav.all().values_list('id', flat=True)
        except TypeError:
            pass
        return context


# News Create
class NewsCreateView(LoginRequiredMixin, CreateView):
    model = mainpage_models.Post
    form_class = forms.NewsCreate
    template_name = 'mainpage/news_create.html'
    success_url = reverse_lazy('mainpage:custom_posts')

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        # form.instance.user = Post.objects.get(user=current_user)
        if form.is_valid():
            if request.user is not None:
                post = Post()
                post.title = form.cleaned_data['title']
                post.preview = form.cleaned_data['preview']
                post.content = form.cleaned_data['content']
                post.user = request.user
                post.save()
                messages.success(
                    self.request,
                    _('Пост успешно создан и отправлен на модерацию.')
                )
            return self.form_valid(form)
        else:
            messages.error(
                self.request,
                _('Пост не был создан. Попробуйте снова.')
            )
            return self.form_invalid(form)


# News Update
class NewsUpdateView(LoginRequiredMixin, UpdateView):
    model = mainpage_models.Post
    template_name = 'mainpage/news_update.html'
    form_class = forms.NewsUpdate
    success_url = reverse_lazy('mainpage:custom_posts')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user or request.user.is_staff:
            return super().get(request, *args, **kwargs)
        else:
            raise Http404


# News Delete
class NewsDeleteView(LoginRequiredMixin, DeleteView):
    model = mainpage_models.Post
    success_url = reverse_lazy('mainpage:custom_posts')
    template_name = 'mainpage/post_confirm_delete.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user or request.user.is_staff:
            return render(request, self.template_name, {'object': self.object})
        else:
            raise Http404  # or return HttpResponse('404_url')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user or request.user.is_staff:
            self.object.delete()
            return redirect('mainpage:custom_posts')
        else:
            raise Http404  # or return HttpResponse('404_url')


# Our news
class CustomPostView(LoginRequiredMixin, FormView):

    model = mainpage_models.Post
    template_name = 'mainpage/our_news.html'

    def get_context_data(self, **kwargs):
        return {'post_items': mainpage_models.Post.objects.filter(
            categories__headline='Наши новости').filter(
            is_published=True)}


# Moderation news
class NewsOnModerationView(LoginRequiredMixin, FormView):

    model = mainpage_models.Post
    template_name = 'mainpage/posts_on_moderation.html'

    def get_context_data(self, **kwargs):
        return {'post_items': mainpage_models.Post.objects.filter(
            categories__headline='Наши новости', is_published=False)}


# Register
class UserRegister(FormView):
    form_class = forms.UserRegForm
    template_name = 'mainpage/registration_form.html'
    success_url = reverse_lazy('mainpage:login')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():

            with transaction.atomic():
                try:
                    user = mainpage_models.User.objects.create(
                        username=form.cleaned_data['username'],
                        password=form.cleaned_data['password2'],
                        email=form.cleaned_data['email'],
                        is_active=False)
                    user.set_password(user.password)
                    from django.utils.timezone import now
                    activation = mainpage_models.Activation(
                        valid_until=now() + timedelta(minutes=2)
                    )
                    activation.set_url()
                    activation.save()
                    user.save()
                    profile = mainpage_models.Profile()
                    profile.activation = activation
                    profile.user = user
                    profile.save()
                except Exception as exc:
                    messages.error(
                        self.request,
                        _('Не удалось создать учётную запись. Обратитесь к администратору.')
                    )
                    raise exc
                else:
                    messages.success(
                        request,
                        _('Учётная запись создана. Уведомление для активации в ящике.')
                    )

                    # send_mail(subject, message, from_email, to_list, fail_silently=True)
                    subject = _('Подтверждение почты')
                    message = user.username + _(', вот ваша cсылка для активации:') + ' {url}'.format(

mainpage/templates/mainpage/change-password.html
{% extends 'mainpage/header.html' %}
{% load i18n %}

{% block title %}
    {{ block.super }}{% trans 'Пароль' %}
{% endblock %}

{% block menu %}
    {% include "mainpage/includes/menu.html" %}
{% endblock %}

{% block content %}

<h1 style="text-align: center; color: rgb(100,100,100); font-weight: bold;">{% trans 'Смена пароля' %}</h1>

<div class="container-fluid ">

    <div class="row">

        <div class="col-sm-8 col-md-push-2">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p>{{ error_message }}</p>
                    {% endif %}
                    {% if messages %}
                      <ul class="messages" >
                        {% for message in messages %}
                          <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                      </ul>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" >
                        {% csrf_token %}
                        {% include 'mainpage/includes/form_template.html' %}
                        <div class="form-group" >
                            <div class="col-sm-10" style="text-align: center">
                                <button type="submit" class="btn btn-success btnform">{% trans 'Ввод' %}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

mainpage/templates/mainpage/favourites.html
{% extends "mainpage/templates/mainpage/header.html" %}

{% load i18n %}

    {% block title %}
        {{ block.super }}{% trans 'Favourites' %}
    {% endblock %}

    {% block menu %}
        {% include "mainpage/includes/menu.html" %}
    {% endblock %}

<br>

{% block content %}

        {% for post in favourite_posts %}
                <ul>
                    <li>
                        <center>
                            <p>
                                <h2>
                                     <a class="anodec" style="font-size: x-large;color: rgb(100,100,100)" href="{{ post.url }}">
                                         {% autoescape off %}
                                             {{ post.title }}
                                         {% endautoescape %}
                                     </a>
                                </h2>
                            </p>
                        </center>
                    </li>

                    <li>
                        <center>
                            <p style="color: rgb(128,128,128)">
                                {{ post.create_date }}
                            </p>
                        </center>
                    </li>
                    <li>
                        <center>
                          {% autoescape off  %}
                              {% if post.pic != None %}
                                  {{ post.pic }}
                              {% endif %}
                          {% endautoescape %}
                        </center>
                    </li>
                    <li>
                    <center>
                        <p>
                            {% autoescape off %}{{ post.preview  }}{% endautoescape %}
                        </p>
                    </center>
                    </li>
                    <li>
                        <center>
                                {% block continue %}
                                    <a style="color:rgb(100,100,100); font-weight: bold;" href="{% url 'mainpage:post' post.pk %}">{% trans 'Продолжение на этом сайте..' %}</a>
                                    <br><br><br><br><br><br><br>
                                {% endblock %}
                        </center>
                    </li>
                </ul>

         {% endfor  %}

        {% if favourite_posts is None %}

            <br>
            <p class="centerr"> {% trans 'У вас пока что нету избранных постов.' %} </p>
            <br>
        {% endif %}

{% endblock %}

mainpage/templates/mainpage/head_js.html
{% load staticfiles %}
{% block js %}
<script type="text/javascript" src="{% static 'js/jquery-3.2.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap_menu.js' %}"></script>
{% endblock %}

mainpage/templates/mainpage/home.html
{% extends "mainpage/templates/mainpage/header.html" %}
{% load i18n %}

    {% block title %}
        {{ block.super }}{% trans 'Jamba' %}
    {% endblock %}
    {% block menu %}
        {% include "mainpage/includes/menu.html" %}
    {% endblock %}

    {% block content %}
        {% include "mainpage/includes/htmlsnippet.html" %}
        {% include "mainpage/post_list.html" %}
        {% include "mainpage/includes/add_posts.html" %}
    {% endblock %}

mainpage/templates/mainpage/login_form.html
{% extends "mainpage/templates/mainpage/header.html" %}
{% load i18n %}

{% block menu %}
    {% include "mainpage/includes/menu.html" %}
{% endblock %}


{% block title %}
    {{ block.super }}{% trans 'Авторизация' %}
{% endblock %}

{% block content %}

<h1 style="text-align: center; color: rgb(100,100,100); font-weight: bold;">{% trans 'Авторизация' %}</h1>

<div class="container-fluid ">
    <div class="row">
        <div class="col-sm-8 col-md-push-2">
            <div class="panel panel-default">
                <div class="panel-body">

                    {% if error_message %}
                        <p>{{ error_message }}</p>
                    {% endif %}
                    {% if messages %}
                      <ul class="messages">
                        {% for message in messages %}
                          <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                      </ul>
                    {% endif %}

                    <form class="form-horizontal" role="form" action="" enctype="multipart/form-data" method="post" >
                        {% csrf_token %}
                        {% include 'mainpage/includes/form_template.html' %}
                        <div class="col-sm-10" style="text-align: center"> <a style="font-size: 90%; color: darkgrey;" href="{% url 'mainpage:password_reset' %}">{% trans 'Забыли пароль?' %} </a></div>

                        <div class="form-group" >
                            <div class="col-sm-10" style="text-align: center">
                                <br>
                                <button type="submit" class="btn btn-success btnform">{% trans 'Зайти' %}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

mainpage/templates/mainpage/post_confirm_delete.html
{% load i18n %}
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Вы уверены, что хотите удалить ' %} "{{ object }}"?</p>
    <input type="submit" value="{% trans 'Удалить' %}" />
    <a href="{% url 'mainpage:custom_posts' %}">{% trans 'Отмена' %}</a>

</form>

mainpage/templates/mainpage/post_detail.html
{% extends "mainpage/templates/mainpage/header.html" %}
{% load i18n %}

{% block menu %}
    {% include "mainpage/includes/menu.html" %}
{% endblock %}

{% block content %}
{% with request.user as current_user %}


{% if user.is_authenticated %}

    {% if post.pk in favs %}

                    <span>
                        <div class="row">
                            <div class="formcenter">

                                        {% if error_message %}
                                            <p>{{ error_message }}</p>
                                        {% endif %}

                                        {% if messages %}
                                          <ul class="messages">
                                            {% for message in messages %}
                                              <li class="{{ message.tags }}">{{ message }}</li>
                                            {% endfor %}
                                          </ul>
                                        {% endif %}

                                    <form role="form"  id="favorite" action="" method="post" >
                                        {% csrf_token %}
                                        {% include 'mainpage/includes/form_template.html' %}
                                            <div class="formcenter" style="text-align: center">
                                                <br>
                                                <button type="submit" id="fav_btn" class="btn btn-default"><span class="glyphicon glyphicon-star-empty"></span> {% trans 'Убрать из избранного' %}</button>
                                            </div>
                                    </form>
                            </div>
                        </div>
                     </span>

    {% else %}

                        <span>
                        <div class="row">
                            <div class="formcenter">
                                        {% if error_message %}
                                            <p>{{ error_message }}</p>
                                        {% endif %}

                                        {% if messages %}
                                          <ul class="messages">
                                            {% for message in messages %}
                                              <li class="{{ message.tags }}">{{ message }}</li>
                                            {% endfor %}
                                          </ul>
                                        {% endif %}

                                    <form role="form"  id="favorite" action="" method="post" >
                                        {% csrf_token %}
                                        {% include 'mainpage/includes/form_template.html' %}
                                            <div class="formcenter" style="text-align: center">
                                                <br>
                                                <button type="submit" id="fav_btn" class="btn btn-default"><span class="glyphicon glyphicon-star"></span> {% trans 'Добавить в избранное' %}</button>
                                            </div>
                                    </form>
                            </div>
                        </div>
                     </span>

    {% endif %}

{% else %}
        <p class="centerr">{% trans 'Вы можете авторизоваться, чтобы иметь возможность сохранять посты в свой профиль!' %}</p>
{% endif %}
    <span class="centerr">
             <p>
                   <h2>
                         <a class="anodec" style="font-size: x-large; color:rgb(100,100,100)" href="{{ post.url }}">
                             {% autoescape off %}
                                 {{ post.title }}
                             {% endautoescape %}
                         </a>
                   </h2>
            </p >
            <p style="color: rgb(128,128,128)">
                {{ post.create_date }}
            </p>
    </span>

    {% autoescape off %}
            {{ post.content }}
    {% endautoescape %}


    {% if current_user == post.user or request.user.is_staff %}

        <p  style="text-align: center">
                    <br>
            {% trans 'У вас есть права на' %}
            <a class="anodec" href="{% url 'mainpage:news_update' post.pk %}"> {% trans 'редактирование' %} </a>
            {% trans 'и' %}
            <a class="anodec" href="{% url 'mainpage:news_delete' post.pk %}"> {% trans 'удаление' %} </a>
            {% trans 'этой новости.' %}
        </p>
    {% endif %}

    {% if post.is_published == False %}
        {% if user.is_staff %}
                        <span>
            <div class="row">
                <div class="formcenter">

                    {% if error_message %}
                        <p>{{ error_message }}</p>
                    {% endif %}

                    {% if messages %}
                      <ul class="messages">
                        {% for message in messages %}
                          <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                      </ul>
                    {% endif %}

                    <form role="form"  id="moderate" action="" method="post" >
                        {% csrf_token %}
                        {% include 'mainpage/includes/form_template.html' %}
                            <div class="formcenter" style="text-align: center">
                                <br>
                                <button type="submit" id="mod_btn" class="btn btn-default"> {% trans 'Опубликовать' %}</button>

                            </div>
                        <br>
                    </form>
                </div>
            </div>
         </span>

        {% endif %}
    {% endif %}
<script type="text/javascript">

$(document).on('submit', '#favorite', function (e) {
    e.preventDefault();
    $.ajax({
        type: 'POST',
        url: 'user/favorited',
        data: {
            pk: {{ post.pk }},
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success:function(info){
            console.log(info)
            console.log(typeof (info))

            if (info["favorited"] === true){
                $('#fav_btn').html('<span class="glyphicon glyphicon-star"></span> Favorited!')
            } else {
                $('#fav_btn').html('<span class="glyphicon glyphicon-star-empty"></span> Unfavorited!')
            }
        }
    })
});
$(document).on('submit', '#moderate', function (e) {
    e.preventDefault();
    $.ajax({
        type: 'POST',
        url: 'user/moderated',
        data: {
            pk: {{ post.pk }},
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success:function(info){
            console.log(info)
            console.log(typeof (info))

            if (info["is_published"] === true){
                $('#mod_btn').html("{% trans 'Пост опубликован!' %}")
            } else {
                $('#mod_btn').html("{% trans 'Публикация отменена!' %}")
            }
        }
    })
})
</script>

{% endwith %}
{% endblock %}

mainpage/templates/mainpage/tut.html
{% extends "mainpage/templates/mainpage/header.html" %}


{% block content %}

{% include "mainpage/postdev_list.html" %}
{% include "mainpage/includes/htmlsnippet.html" %}

{% endblock %}